# Generated by Django 4.0.5 on 2022-07-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='twitter_account',
            new_name='twitter_username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fist_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
